// Common React import
import React from 'react';

// React Icons imports (deduplicated)
import {
  FaHeartbeat,
  FaShoppingCart,
  FaUniversity,
  FaBookReader,
  FaBuilding,
  FaPlaneDeparture,
  FaTools,
  FaRocket,
  FaCar,
  FaServer,
  FaCogs,
  FaShieldAlt,
  FaLaptopCode,
  FaBriefcase,
  FaHotel,
  FaBullhorn,
  FaChartLine,
  FaGraduationCap,
  FaCloud,
  FaTruck,
  FaRobot,
  FaSearch,
  FaIndustry,
  FaCloudShieldAlt,
  FaEye,
  FaClipboardCheck,
  FaDatabase,
  FaBroom,
  FaLightbulb,
  FaFileAlt,
  FaNetworkWired,
  FaBrain,
  FaVrCardboard,
  FaBug,
  FaTachometerAlt,
  FaUserCheck,
  FaClipboardList,
  FaSitemap,
  FaPalette,
  FaCode,
  FaCodeBranch,
  FaDocker,
  FaMobileAlt,
  FaCloudUploadAlt,
  FaSync,
  FaListAlt,
  FaPenFancy,
  FaShareAlt,
  FaTasks,
  FaChalkboardTeacher,
  FaDraftingCompass,
  FaProjectDiagram,
  FaUsers,
  FaChartBar,
  FaChartPie,
  FaCheckCircle
} from 'react-icons/fa';

// Deduplicated icon map
export const iconMap = {
  FaSearch: FaSearch,
  FaHeartbeat: FaHeartbeat,
  FaShoppingCart: FaShoppingCart,
  FaUniversity: FaUniversity,
  FaBookReader: FaBookReader,
  FaBuilding: FaBuilding,
  FaPlaneDeparture: FaPlaneDeparture,
  FaTools: FaTools,
  FaRocket: FaRocket,
  FaCar: FaCar,
  FaServer: FaServer,
  FaCogs: FaCogs,
  FaShieldAlt: FaShieldAlt,
  FaLaptopCode: FaLaptopCode,
  FaBriefcase: FaBriefcase,
  FaHotel: FaHotel,
  FaBullhorn: FaBullhorn,
  FaChartLine: FaChartLine,
  FaGraduationCap: FaGraduationCap,
  FaCloud: FaCloud,
  FaTruck: FaTruck,
  FaRobot: FaRobot,
  FaIndustry: FaIndustry,
  FaCloudShieldAlt: FaCloudShieldAlt,
  FaEye: FaEye,
  FaClipboardCheck: FaClipboardCheck,
  FaChalkboardTeacher: FaChalkboardTeacher,
  FaDatabase: FaDatabase,
  FaBroom: FaBroom,
  FaProjectDiagram: FaProjectDiagram,
  FaLightbulb: FaLightbulb,
  FaFileAlt: FaFileAlt,
  FaNetworkWired: FaNetworkWired,
  FaBrain: FaBrain,
  FaVrCardboard: FaVrCardboard,
  FaBug: FaBug,
  FaTachometerAlt: FaTachometerAlt,
  FaUserCheck: FaUserCheck,
  FaClipboardList: FaClipboardList,
  FaDraftingCompass: FaDraftingCompass,
  FaSitemap: FaSitemap,
  FaPalette: FaPalette,
  FaCode: FaCode,
  FaCodeBranch: FaCodeBranch,
  FaDocker: FaDocker,
  FaMobileAlt: FaMobileAlt,
  FaCloudUploadAlt: FaCloudUploadAlt,
  FaSync: FaSync,
  FaListAlt: FaListAlt,
  FaPenFancy: FaPenFancy,
  FaShareAlt: FaShareAlt,
  FaTasks: FaTasks,
  FaUsers:FaUsers,
  FaChartBar:FaChartBar,
  FaChartPie:FaChartPie,
  FaCheckCircle:FaCheckCircle
};
